import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Terms of Service | StepEase",
    description: "Terms of Service for StepEase - AI-powered SOP builder",
}

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-background">
            <div className="max-w-3xl mx-auto px-4 py-16">
                <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>

                <div className="prose prose-gray dark:prose-invert max-w-none space-y-6">
                    <p className="text-muted-foreground">
                        Last updated: January 21, 2026
                    </p>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
                        <p>
                            By accessing and using StepEase, you accept and agree to be bound by these
                            Terms of Service. If you do not agree to these terms, please do not use our service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">2. Description of Service</h2>
                        <p>
                            StepEase is an AI-powered platform that helps users create, manage, and improve
                            Standard Operating Procedures (SOPs). The service includes:
                        </p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Conversational AI for SOP creation</li>
                            <li>Document analysis and improvement suggestions</li>
                            <li>Export functionality in multiple formats</li>
                            <li>Cloud storage for your documents</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">3. User Accounts</h2>
                        <p>
                            You are responsible for maintaining the confidentiality of your account
                            and password. You agree to accept responsibility for all activities that
                            occur under your account.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">4. User Content</h2>
                        <p>
                            You retain ownership of all content you create using StepEase. By using
                            our service, you grant us a license to store and process your content
                            solely for the purpose of providing the service.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">5. Acceptable Use</h2>
                        <p>You agree not to:</p>
                        <ul className="list-disc pl-6 space-y-2">
                            <li>Use the service for any illegal purpose</li>
                            <li>Upload malicious content or code</li>
                            <li>Attempt to gain unauthorized access to our systems</li>
                            <li>Interfere with other users&apos; use of the service</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">6. AI-Generated Content</h2>
                        <p>
                            Content generated by our AI assistant is provided as-is. While we strive
                            for accuracy, you are responsible for reviewing and verifying all
                            AI-generated SOPs before use in your organization.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">7. Limitation of Liability</h2>
                        <p>
                            StepEase is provided &quot;as is&quot; without warranty of any kind. We shall not
                            be liable for any indirect, incidental, special, or consequential damages.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">8. Changes to Terms</h2>
                        <p>
                            We reserve the right to modify these terms at any time. We will notify
                            users of significant changes via email or through the application.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold mt-8 mb-4">9. Contact</h2>
                        <p>
                            For questions about these Terms, contact us at{" "}
                            <a href="mailto:legal@stepease.com" className="text-primary hover:underline">
                                legal@stepease.com
                            </a>
                        </p>
                    </section>
                </div>
            </div>
        </div>
    )
}
